export const WORLD_WIDTH = 1400;
export const WORLD_HEIGHT = 860;

export const OWNER_NEUTRAL = "neutral";

export const CELL_TYPES = {
  small: { radius: 28, growth: 2.25, capacity: 42 },
  medium: { radius: 36, growth: 3.25, capacity: 64 },
  large: { radius: 46, growth: 4.55, capacity: 96 },
};

export const FACTIONS = {
  player: {
    id: "player",
    label: "Player",
    color: "#82c96f",
    glow: "rgba(130, 201, 111, 0.36)",
    isHuman: true,
  },
  crimson: {
    id: "crimson",
    label: "Coral Burrow",
    color: "#eb8c7a",
    glow: "rgba(235, 140, 122, 0.36)",
    isHuman: false,
  },
  gold: {
    id: "gold",
    label: "Amber Grove",
    color: "#f0c76f",
    glow: "rgba(240, 199, 111, 0.36)",
    isHuman: false,
  },
  violet: {
    id: "violet",
    label: "Lavender Hollow",
    color: "#b7a0ef",
    glow: "rgba(183, 160, 239, 0.36)",
    isHuman: false,
  },
  cerulean: {
    id: "cerulean",
    label: "Blue Brook",
    color: "#84cbe6",
    glow: "rgba(132, 203, 230, 0.36)",
    isHuman: false,
  },
  neutral: {
    id: "neutral",
    label: "Wild Patch",
    color: "#c5baa1",
    glow: "rgba(197, 186, 161, 0.24)",
    isHuman: false,
  },
};

export const DIFFICULTIES = {
  easy: {
    id: "easy",
    label: "Easy",
    reactionMin: 1.15,
    reactionMax: 1.6,
    coordination: 2,
    reserveFactor: 0.24,
    minSendable: 8,
    attackMargin: 1.34,
    expansionMargin: 1.05,
    defenseMargin: 0.9,
    expansionWeight: 1.42,
    attackWeight: 0.54,
    productionWeight: 0.8,
    supportPenalty: 11,
    stageEnabled: false,
    stageThreshold: 0,
    threatHorizon: 2.8,
    cooldownBase: 1.25,
    cooldownPerSource: 0.22,
    idleMin: 0.8,
    idleMax: 1.2,
    frontierRadius: 260,
    attackProgressGate: 0.48,
    attackLeadGate: 1.18,
    freeTargetSupport: 0,
    freeTargetCost: 0.56,
    stageProgressGate: 0.58,
  },
  normal: {
    id: "normal",
    label: "Normal",
    reactionMin: 0.82,
    reactionMax: 1.16,
    coordination: 3,
    reserveFactor: 0.18,
    minSendable: 6,
    attackMargin: 1.16,
    expansionMargin: 1.02,
    defenseMargin: 0.84,
    expansionWeight: 1,
    attackWeight: 1,
    productionWeight: 1,
    supportPenalty: 7,
    stageEnabled: true,
    stageThreshold: 0.18,
    threatHorizon: 3.4,
    cooldownBase: 0.92,
    cooldownPerSource: 0.18,
    idleMin: 0.6,
    idleMax: 0.95,
    frontierRadius: 285,
    attackProgressGate: 0.3,
    attackLeadGate: 1.02,
    freeTargetSupport: 1,
    freeTargetCost: 0.78,
    stageProgressGate: 0.4,
  },
  hard: {
    id: "hard",
    label: "Hard",
    reactionMin: 0.62,
    reactionMax: 0.92,
    coordination: 4,
    reserveFactor: 0.13,
    minSendable: 5,
    attackMargin: 1.06,
    expansionMargin: 0.98,
    defenseMargin: 0.78,
    expansionWeight: 0.84,
    attackWeight: 1.24,
    productionWeight: 1.22,
    supportPenalty: 4,
    stageEnabled: true,
    stageThreshold: 0.08,
    threatHorizon: 4.2,
    cooldownBase: 0.72,
    cooldownPerSource: 0.15,
    idleMin: 0.42,
    idleMax: 0.7,
    frontierRadius: 320,
    attackProgressGate: 0.18,
    attackLeadGate: 0.92,
    freeTargetSupport: 2,
    freeTargetCost: 1.02,
    stageProgressGate: 0.26,
  },
};

export const GAME_RULES = {
  sendFraction: 0.5,
  minGarrison: 1,
  overflowMultiplier: 1.35,
  overflowDecay: 1.9,
  neutralTravelFactor: 0.84,
  speedOptions: [1, 1.5, 2],
};

export function factionName(ownerId) {
  return FACTIONS[ownerId]?.label ?? ownerId;
}
